<?php

/**
 * @file
 * Contains awe_builder.module..
 */

use Drupal\block\Entity\Block;
use Drupal\Component\Serialization\Json;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Template\Attribute;


/**
 * Implements hook_theme().
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function awe_team_theme($existing, $type, $theme, $path) {
  $theme = [];

  $theme['el_team'] = [
    'path' => $path,
    'variables' => [
      'el_settings' => [],
      'el_extra_data' => [],
      'el_animation' => [],
      'el_wrap_class' => '',
    ]
  ];

  return $theme;
}

function awe_team_preprocess_el_team(&$vars) {
  _awebuilder_set_all_part_to_variable($vars);
}