<?php

function nav_mobile_theme($existing, $type, $theme, $path) {
  return array('nav_mobile_template' =>                  // this is the name of the template
           array(
            'variables' => array(
                'logo' => '',
                'menu' => null,
                'sitename' => null,
                'search' => null,
                'social' => null,
                'base_path' => null
            ),
        )
    );
}